/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as DocumentIndexRouteImport } from './routes/document/index'
import { Route as ComplaintIndexRouteImport } from './routes/complaint/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as NewsIdRouteImport } from './routes/news/$id'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ActivityIdRouteImport } from './routes/activity/$id'
import { Route as AdminNewsIndexRouteImport } from './routes/admin/news/index'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AboutHistoryIndexRouteImport } from './routes/about/history/index'
import { Route as AboutDoctorIndexRouteImport } from './routes/about/doctor/index'
import { Route as AboutContactIndexRouteImport } from './routes/about/contact/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentIndexRoute = DocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintIndexRoute = ComplaintIndexRouteImport.update({
  id: '/complaint/',
  path: '/complaint/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsIndexRoute = AdminNewsIndexRouteImport.update({
  id: '/admin/news/',
  path: '/admin/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/admin/login/',
  path: '/admin/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutHistoryIndexRoute = AboutHistoryIndexRouteImport.update({
  id: '/about/history/',
  path: '/about/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDoctorIndexRoute = AboutDoctorIndexRouteImport.update({
  id: '/about/doctor/',
  path: '/about/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutContactIndexRoute = AboutContactIndexRouteImport.update({
  id: '/about/contact/',
  path: '/about/contact/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity/$id': typeof ActivityIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/news/$id': typeof NewsIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/complaint/': typeof ComplaintIndexRoute
  '/document/': typeof DocumentIndexRoute
  '/news/': typeof NewsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/about/contact/': typeof AboutContactIndexRoute
  '/about/doctor/': typeof AboutDoctorIndexRoute
  '/about/history/': typeof AboutHistoryIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity/$id': typeof ActivityIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/news/$id': typeof NewsIdRoute
  '/activity': typeof ActivityIndexRoute
  '/complaint': typeof ComplaintIndexRoute
  '/document': typeof DocumentIndexRoute
  '/news': typeof NewsIndexRoute
  '/service': typeof ServiceIndexRoute
  '/about/contact': typeof AboutContactIndexRoute
  '/about/doctor': typeof AboutDoctorIndexRoute
  '/about/history': typeof AboutHistoryIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/admin/news': typeof AdminNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity/$id': typeof ActivityIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/news/$id': typeof NewsIdRoute
  '/activity/': typeof ActivityIndexRoute
  '/complaint/': typeof ComplaintIndexRoute
  '/document/': typeof DocumentIndexRoute
  '/news/': typeof NewsIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/about/contact/': typeof AboutContactIndexRoute
  '/about/doctor/': typeof AboutDoctorIndexRoute
  '/about/history/': typeof AboutHistoryIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/admin/news/': typeof AdminNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity/$id'
    | '/admin/dashboard'
    | '/news/$id'
    | '/activity/'
    | '/complaint/'
    | '/document/'
    | '/news/'
    | '/service/'
    | '/about/contact/'
    | '/about/doctor/'
    | '/about/history/'
    | '/admin/login/'
    | '/admin/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity/$id'
    | '/admin/dashboard'
    | '/news/$id'
    | '/activity'
    | '/complaint'
    | '/document'
    | '/news'
    | '/service'
    | '/about/contact'
    | '/about/doctor'
    | '/about/history'
    | '/admin/login'
    | '/admin/news'
  id:
    | '__root__'
    | '/'
    | '/activity/$id'
    | '/admin/dashboard'
    | '/news/$id'
    | '/activity/'
    | '/complaint/'
    | '/document/'
    | '/news/'
    | '/service/'
    | '/about/contact/'
    | '/about/doctor/'
    | '/about/history/'
    | '/admin/login/'
    | '/admin/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityIdRoute: typeof ActivityIdRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  NewsIdRoute: typeof NewsIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  ComplaintIndexRoute: typeof ComplaintIndexRoute
  DocumentIndexRoute: typeof DocumentIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
  AboutContactIndexRoute: typeof AboutContactIndexRoute
  AboutDoctorIndexRoute: typeof AboutDoctorIndexRoute
  AboutHistoryIndexRoute: typeof AboutHistoryIndexRoute
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
  AdminNewsIndexRoute: typeof AdminNewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/': {
      id: '/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document/': {
      id: '/document/'
      path: '/document'
      fullPath: '/document/'
      preLoaderRoute: typeof DocumentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint/': {
      id: '/complaint/'
      path: '/complaint'
      fullPath: '/complaint/'
      preLoaderRoute: typeof ComplaintIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/news/': {
      id: '/admin/news/'
      path: '/admin/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminNewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/admin/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/history/': {
      id: '/about/history/'
      path: '/about/history'
      fullPath: '/about/history/'
      preLoaderRoute: typeof AboutHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/doctor/': {
      id: '/about/doctor/'
      path: '/about/doctor'
      fullPath: '/about/doctor/'
      preLoaderRoute: typeof AboutDoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/contact/': {
      id: '/about/contact/'
      path: '/about/contact'
      fullPath: '/about/contact/'
      preLoaderRoute: typeof AboutContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityIdRoute: ActivityIdRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  NewsIdRoute: NewsIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  ComplaintIndexRoute: ComplaintIndexRoute,
  DocumentIndexRoute: DocumentIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ServiceIndexRoute: ServiceIndexRoute,
  AboutContactIndexRoute: AboutContactIndexRoute,
  AboutDoctorIndexRoute: AboutDoctorIndexRoute,
  AboutHistoryIndexRoute: AboutHistoryIndexRoute,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
  AdminNewsIndexRoute: AdminNewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
