/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as UserServiceIndexRouteImport } from './routes/_user/service/index'
import { Route as UserNewsIndexRouteImport } from './routes/_user/news/index'
import { Route as UserItaIndexRouteImport } from './routes/_user/ita/index'
import { Route as UserDocumentIndexRouteImport } from './routes/_user/document/index'
import { Route as UserComplaintIndexRouteImport } from './routes/_user/complaint/index'
import { Route as UserActivityIndexRouteImport } from './routes/_user/activity/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as UserNewsIdRouteImport } from './routes/_user/news/$id'
import { Route as UserItaCreateRouteImport } from './routes/_user/ita/create'
import { Route as UserActivityIdRouteImport } from './routes/_user/activity/$id'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as UserAboutHistoryIndexRouteImport } from './routes/_user/about/history/index'
import { Route as UserAboutDoctorIndexRouteImport } from './routes/_user/about/doctor/index'
import { Route as UserAboutContactIndexRouteImport } from './routes/_user/about/contact/index'
import { Route as AdminAdminStaffserviceIndexRouteImport } from './routes/_admin/admin/staffservice/index'
import { Route as AdminAdminPopupIndexRouteImport } from './routes/_admin/admin/popup/index'
import { Route as AdminAdminPersonnelIndexRouteImport } from './routes/_admin/admin/personnel/index'
import { Route as AdminAdminNewsIndexRouteImport } from './routes/_admin/admin/news/index'
import { Route as AdminAdminMoitIndexRouteImport } from './routes/_admin/admin/moit/index'
import { Route as AdminAdminLoginIndexRouteImport } from './routes/_admin/admin/login/index'
import { Route as AdminAdminActivityIndexRouteImport } from './routes/_admin/admin/activity/index'
import { Route as AdminAdminITAIndexRouteImport } from './routes/_admin/admin/ITA/index'
import { Route as AdminAdminPersonnelCreateRouteImport } from './routes/_admin/admin/personnel/create'
import { Route as AdminAdminEmployeeUsermanetmintRouteImport } from './routes/_admin/admin/employee/usermanetmint'
import { Route as AdminAdminITACreateRouteImport } from './routes/_admin/admin/ITA/create'
import { Route as AdminAdminNewsNewsSummaryRouteImport } from './routes/_admin/admin/news/news.summary'
import { Route as AdminAdminEmployeeStaffserviceSummaryRouteImport } from './routes/_admin/admin/employee/staffservice.summary'
import { Route as AdminAdminActivityActivitySummaryRouteImport } from './routes/_admin/admin/activity/activity.summary'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserServiceIndexRoute = UserServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserNewsIndexRoute = UserNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserItaIndexRoute = UserItaIndexRouteImport.update({
  id: '/ita/',
  path: '/ita/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDocumentIndexRoute = UserDocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserComplaintIndexRoute = UserComplaintIndexRouteImport.update({
  id: '/complaint/',
  path: '/complaint/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserActivityIndexRoute = UserActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserNewsIdRoute = UserNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserItaCreateRoute = UserItaCreateRouteImport.update({
  id: '/ita/create',
  path: '/ita/create',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserActivityIdRoute = UserActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserAboutHistoryIndexRoute = UserAboutHistoryIndexRouteImport.update({
  id: '/about/history/',
  path: '/about/history/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAboutDoctorIndexRoute = UserAboutDoctorIndexRouteImport.update({
  id: '/about/doctor/',
  path: '/about/doctor/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAboutContactIndexRoute = UserAboutContactIndexRouteImport.update({
  id: '/about/contact/',
  path: '/about/contact/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAdminStaffserviceIndexRoute =
  AdminAdminStaffserviceIndexRouteImport.update({
    id: '/admin/staffservice/',
    path: '/admin/staffservice/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminPopupIndexRoute = AdminAdminPopupIndexRouteImport.update({
  id: '/admin/popup/',
  path: '/admin/popup/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPersonnelIndexRoute =
  AdminAdminPersonnelIndexRouteImport.update({
    id: '/admin/personnel/',
    path: '/admin/personnel/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminNewsIndexRoute = AdminAdminNewsIndexRouteImport.update({
  id: '/admin/news/',
  path: '/admin/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminMoitIndexRoute = AdminAdminMoitIndexRouteImport.update({
  id: '/admin/moit/',
  path: '/admin/moit/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLoginIndexRoute = AdminAdminLoginIndexRouteImport.update({
  id: '/admin/login/',
  path: '/admin/login/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminActivityIndexRoute = AdminAdminActivityIndexRouteImport.update({
  id: '/admin/activity/',
  path: '/admin/activity/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminITAIndexRoute = AdminAdminITAIndexRouteImport.update({
  id: '/admin/ITA/',
  path: '/admin/ITA/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminPersonnelCreateRoute =
  AdminAdminPersonnelCreateRouteImport.update({
    id: '/admin/personnel/create',
    path: '/admin/personnel/create',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminEmployeeUsermanetmintRoute =
  AdminAdminEmployeeUsermanetmintRouteImport.update({
    id: '/admin/employee/usermanetmint',
    path: '/admin/employee/usermanetmint',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminITACreateRoute = AdminAdminITACreateRouteImport.update({
  id: '/admin/ITA/create',
  path: '/admin/ITA/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminNewsNewsSummaryRoute =
  AdminAdminNewsNewsSummaryRouteImport.update({
    id: '/admin/news/news/summary',
    path: '/admin/news/news/summary',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminEmployeeStaffserviceSummaryRoute =
  AdminAdminEmployeeStaffserviceSummaryRouteImport.update({
    id: '/admin/employee/staffservice/summary',
    path: '/admin/employee/staffservice/summary',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminActivityActivitySummaryRoute =
  AdminAdminActivityActivitySummaryRouteImport.update({
    id: '/admin/activity/activity/summary',
    path: '/admin/activity/activity/summary',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof UserIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/activity/$id': typeof UserActivityIdRoute
  '/ita/create': typeof UserItaCreateRoute
  '/news/$id': typeof UserNewsIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/activity/': typeof UserActivityIndexRoute
  '/complaint/': typeof UserComplaintIndexRoute
  '/document/': typeof UserDocumentIndexRoute
  '/ita/': typeof UserItaIndexRoute
  '/news/': typeof UserNewsIndexRoute
  '/service/': typeof UserServiceIndexRoute
  '/admin/ITA/create': typeof AdminAdminITACreateRoute
  '/admin/employee/usermanetmint': typeof AdminAdminEmployeeUsermanetmintRoute
  '/admin/personnel/create': typeof AdminAdminPersonnelCreateRoute
  '/admin/ITA/': typeof AdminAdminITAIndexRoute
  '/admin/activity/': typeof AdminAdminActivityIndexRoute
  '/admin/login/': typeof AdminAdminLoginIndexRoute
  '/admin/moit/': typeof AdminAdminMoitIndexRoute
  '/admin/news/': typeof AdminAdminNewsIndexRoute
  '/admin/personnel/': typeof AdminAdminPersonnelIndexRoute
  '/admin/popup/': typeof AdminAdminPopupIndexRoute
  '/admin/staffservice/': typeof AdminAdminStaffserviceIndexRoute
  '/about/contact/': typeof UserAboutContactIndexRoute
  '/about/doctor/': typeof UserAboutDoctorIndexRoute
  '/about/history/': typeof UserAboutHistoryIndexRoute
  '/admin/activity/activity/summary': typeof AdminAdminActivityActivitySummaryRoute
  '/admin/employee/staffservice/summary': typeof AdminAdminEmployeeStaffserviceSummaryRoute
  '/admin/news/news/summary': typeof AdminAdminNewsNewsSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof UserIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/activity/$id': typeof UserActivityIdRoute
  '/ita/create': typeof UserItaCreateRoute
  '/news/$id': typeof UserNewsIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/activity': typeof UserActivityIndexRoute
  '/complaint': typeof UserComplaintIndexRoute
  '/document': typeof UserDocumentIndexRoute
  '/ita': typeof UserItaIndexRoute
  '/news': typeof UserNewsIndexRoute
  '/service': typeof UserServiceIndexRoute
  '/admin/ITA/create': typeof AdminAdminITACreateRoute
  '/admin/employee/usermanetmint': typeof AdminAdminEmployeeUsermanetmintRoute
  '/admin/personnel/create': typeof AdminAdminPersonnelCreateRoute
  '/admin/ITA': typeof AdminAdminITAIndexRoute
  '/admin/activity': typeof AdminAdminActivityIndexRoute
  '/admin/login': typeof AdminAdminLoginIndexRoute
  '/admin/moit': typeof AdminAdminMoitIndexRoute
  '/admin/news': typeof AdminAdminNewsIndexRoute
  '/admin/personnel': typeof AdminAdminPersonnelIndexRoute
  '/admin/popup': typeof AdminAdminPopupIndexRoute
  '/admin/staffservice': typeof AdminAdminStaffserviceIndexRoute
  '/about/contact': typeof UserAboutContactIndexRoute
  '/about/doctor': typeof UserAboutDoctorIndexRoute
  '/about/history': typeof UserAboutHistoryIndexRoute
  '/admin/activity/activity/summary': typeof AdminAdminActivityActivitySummaryRoute
  '/admin/employee/staffservice/summary': typeof AdminAdminEmployeeStaffserviceSummaryRoute
  '/admin/news/news/summary': typeof AdminAdminNewsNewsSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/_user/': typeof UserIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_user/activity/$id': typeof UserActivityIdRoute
  '/_user/ita/create': typeof UserItaCreateRoute
  '/_user/news/$id': typeof UserNewsIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_user/activity/': typeof UserActivityIndexRoute
  '/_user/complaint/': typeof UserComplaintIndexRoute
  '/_user/document/': typeof UserDocumentIndexRoute
  '/_user/ita/': typeof UserItaIndexRoute
  '/_user/news/': typeof UserNewsIndexRoute
  '/_user/service/': typeof UserServiceIndexRoute
  '/_admin/admin/ITA/create': typeof AdminAdminITACreateRoute
  '/_admin/admin/employee/usermanetmint': typeof AdminAdminEmployeeUsermanetmintRoute
  '/_admin/admin/personnel/create': typeof AdminAdminPersonnelCreateRoute
  '/_admin/admin/ITA/': typeof AdminAdminITAIndexRoute
  '/_admin/admin/activity/': typeof AdminAdminActivityIndexRoute
  '/_admin/admin/login/': typeof AdminAdminLoginIndexRoute
  '/_admin/admin/moit/': typeof AdminAdminMoitIndexRoute
  '/_admin/admin/news/': typeof AdminAdminNewsIndexRoute
  '/_admin/admin/personnel/': typeof AdminAdminPersonnelIndexRoute
  '/_admin/admin/popup/': typeof AdminAdminPopupIndexRoute
  '/_admin/admin/staffservice/': typeof AdminAdminStaffserviceIndexRoute
  '/_user/about/contact/': typeof UserAboutContactIndexRoute
  '/_user/about/doctor/': typeof UserAboutDoctorIndexRoute
  '/_user/about/history/': typeof UserAboutHistoryIndexRoute
  '/_admin/admin/activity/activity/summary': typeof AdminAdminActivityActivitySummaryRoute
  '/_admin/admin/employee/staffservice/summary': typeof AdminAdminEmployeeStaffserviceSummaryRoute
  '/_admin/admin/news/news/summary': typeof AdminAdminNewsNewsSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/activity/$id'
    | '/ita/create'
    | '/news/$id'
    | '/admin/'
    | '/activity/'
    | '/complaint/'
    | '/document/'
    | '/ita/'
    | '/news/'
    | '/service/'
    | '/admin/ITA/create'
    | '/admin/employee/usermanetmint'
    | '/admin/personnel/create'
    | '/admin/ITA/'
    | '/admin/activity/'
    | '/admin/login/'
    | '/admin/moit/'
    | '/admin/news/'
    | '/admin/personnel/'
    | '/admin/popup/'
    | '/admin/staffservice/'
    | '/about/contact/'
    | '/about/doctor/'
    | '/about/history/'
    | '/admin/activity/activity/summary'
    | '/admin/employee/staffservice/summary'
    | '/admin/news/news/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/activity/$id'
    | '/ita/create'
    | '/news/$id'
    | '/admin'
    | '/activity'
    | '/complaint'
    | '/document'
    | '/ita'
    | '/news'
    | '/service'
    | '/admin/ITA/create'
    | '/admin/employee/usermanetmint'
    | '/admin/personnel/create'
    | '/admin/ITA'
    | '/admin/activity'
    | '/admin/login'
    | '/admin/moit'
    | '/admin/news'
    | '/admin/personnel'
    | '/admin/popup'
    | '/admin/staffservice'
    | '/about/contact'
    | '/about/doctor'
    | '/about/history'
    | '/admin/activity/activity/summary'
    | '/admin/employee/staffservice/summary'
    | '/admin/news/news/summary'
  id:
    | '__root__'
    | '/_admin'
    | '/_user'
    | '/_user/'
    | '/_admin/admin/dashboard'
    | '/_user/activity/$id'
    | '/_user/ita/create'
    | '/_user/news/$id'
    | '/_admin/admin/'
    | '/_user/activity/'
    | '/_user/complaint/'
    | '/_user/document/'
    | '/_user/ita/'
    | '/_user/news/'
    | '/_user/service/'
    | '/_admin/admin/ITA/create'
    | '/_admin/admin/employee/usermanetmint'
    | '/_admin/admin/personnel/create'
    | '/_admin/admin/ITA/'
    | '/_admin/admin/activity/'
    | '/_admin/admin/login/'
    | '/_admin/admin/moit/'
    | '/_admin/admin/news/'
    | '/_admin/admin/personnel/'
    | '/_admin/admin/popup/'
    | '/_admin/admin/staffservice/'
    | '/_user/about/contact/'
    | '/_user/about/doctor/'
    | '/_user/about/history/'
    | '/_admin/admin/activity/activity/summary'
    | '/_admin/admin/employee/staffservice/summary'
    | '/_admin/admin/news/news/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/service/': {
      id: '/_user/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof UserServiceIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/news/': {
      id: '/_user/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof UserNewsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/ita/': {
      id: '/_user/ita/'
      path: '/ita'
      fullPath: '/ita/'
      preLoaderRoute: typeof UserItaIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/document/': {
      id: '/_user/document/'
      path: '/document'
      fullPath: '/document/'
      preLoaderRoute: typeof UserDocumentIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/complaint/': {
      id: '/_user/complaint/'
      path: '/complaint'
      fullPath: '/complaint/'
      preLoaderRoute: typeof UserComplaintIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/activity/': {
      id: '/_user/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof UserActivityIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/news/$id': {
      id: '/_user/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof UserNewsIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/ita/create': {
      id: '/_user/ita/create'
      path: '/ita/create'
      fullPath: '/ita/create'
      preLoaderRoute: typeof UserItaCreateRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/activity/$id': {
      id: '/_user/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof UserActivityIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/about/history/': {
      id: '/_user/about/history/'
      path: '/about/history'
      fullPath: '/about/history/'
      preLoaderRoute: typeof UserAboutHistoryIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/about/doctor/': {
      id: '/_user/about/doctor/'
      path: '/about/doctor'
      fullPath: '/about/doctor/'
      preLoaderRoute: typeof UserAboutDoctorIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/about/contact/': {
      id: '/_user/about/contact/'
      path: '/about/contact'
      fullPath: '/about/contact/'
      preLoaderRoute: typeof UserAboutContactIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_admin/admin/staffservice/': {
      id: '/_admin/admin/staffservice/'
      path: '/admin/staffservice'
      fullPath: '/admin/staffservice/'
      preLoaderRoute: typeof AdminAdminStaffserviceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/popup/': {
      id: '/_admin/admin/popup/'
      path: '/admin/popup'
      fullPath: '/admin/popup/'
      preLoaderRoute: typeof AdminAdminPopupIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/personnel/': {
      id: '/_admin/admin/personnel/'
      path: '/admin/personnel'
      fullPath: '/admin/personnel/'
      preLoaderRoute: typeof AdminAdminPersonnelIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/news/': {
      id: '/_admin/admin/news/'
      path: '/admin/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminAdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/moit/': {
      id: '/_admin/admin/moit/'
      path: '/admin/moit'
      fullPath: '/admin/moit/'
      preLoaderRoute: typeof AdminAdminMoitIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/login/': {
      id: '/_admin/admin/login/'
      path: '/admin/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof AdminAdminLoginIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/activity/': {
      id: '/_admin/admin/activity/'
      path: '/admin/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AdminAdminActivityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/ITA/': {
      id: '/_admin/admin/ITA/'
      path: '/admin/ITA'
      fullPath: '/admin/ITA/'
      preLoaderRoute: typeof AdminAdminITAIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/personnel/create': {
      id: '/_admin/admin/personnel/create'
      path: '/admin/personnel/create'
      fullPath: '/admin/personnel/create'
      preLoaderRoute: typeof AdminAdminPersonnelCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/employee/usermanetmint': {
      id: '/_admin/admin/employee/usermanetmint'
      path: '/admin/employee/usermanetmint'
      fullPath: '/admin/employee/usermanetmint'
      preLoaderRoute: typeof AdminAdminEmployeeUsermanetmintRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/ITA/create': {
      id: '/_admin/admin/ITA/create'
      path: '/admin/ITA/create'
      fullPath: '/admin/ITA/create'
      preLoaderRoute: typeof AdminAdminITACreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/news/news/summary': {
      id: '/_admin/admin/news/news/summary'
      path: '/admin/news/news/summary'
      fullPath: '/admin/news/news/summary'
      preLoaderRoute: typeof AdminAdminNewsNewsSummaryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/employee/staffservice/summary': {
      id: '/_admin/admin/employee/staffservice/summary'
      path: '/admin/employee/staffservice/summary'
      fullPath: '/admin/employee/staffservice/summary'
      preLoaderRoute: typeof AdminAdminEmployeeStaffserviceSummaryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/activity/activity/summary': {
      id: '/_admin/admin/activity/activity/summary'
      path: '/admin/activity/activity/summary'
      fullPath: '/admin/activity/activity/summary'
      preLoaderRoute: typeof AdminAdminActivityActivitySummaryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminITACreateRoute: typeof AdminAdminITACreateRoute
  AdminAdminEmployeeUsermanetmintRoute: typeof AdminAdminEmployeeUsermanetmintRoute
  AdminAdminPersonnelCreateRoute: typeof AdminAdminPersonnelCreateRoute
  AdminAdminITAIndexRoute: typeof AdminAdminITAIndexRoute
  AdminAdminActivityIndexRoute: typeof AdminAdminActivityIndexRoute
  AdminAdminLoginIndexRoute: typeof AdminAdminLoginIndexRoute
  AdminAdminMoitIndexRoute: typeof AdminAdminMoitIndexRoute
  AdminAdminNewsIndexRoute: typeof AdminAdminNewsIndexRoute
  AdminAdminPersonnelIndexRoute: typeof AdminAdminPersonnelIndexRoute
  AdminAdminPopupIndexRoute: typeof AdminAdminPopupIndexRoute
  AdminAdminStaffserviceIndexRoute: typeof AdminAdminStaffserviceIndexRoute
  AdminAdminActivityActivitySummaryRoute: typeof AdminAdminActivityActivitySummaryRoute
  AdminAdminEmployeeStaffserviceSummaryRoute: typeof AdminAdminEmployeeStaffserviceSummaryRoute
  AdminAdminNewsNewsSummaryRoute: typeof AdminAdminNewsNewsSummaryRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminITACreateRoute: AdminAdminITACreateRoute,
  AdminAdminEmployeeUsermanetmintRoute: AdminAdminEmployeeUsermanetmintRoute,
  AdminAdminPersonnelCreateRoute: AdminAdminPersonnelCreateRoute,
  AdminAdminITAIndexRoute: AdminAdminITAIndexRoute,
  AdminAdminActivityIndexRoute: AdminAdminActivityIndexRoute,
  AdminAdminLoginIndexRoute: AdminAdminLoginIndexRoute,
  AdminAdminMoitIndexRoute: AdminAdminMoitIndexRoute,
  AdminAdminNewsIndexRoute: AdminAdminNewsIndexRoute,
  AdminAdminPersonnelIndexRoute: AdminAdminPersonnelIndexRoute,
  AdminAdminPopupIndexRoute: AdminAdminPopupIndexRoute,
  AdminAdminStaffserviceIndexRoute: AdminAdminStaffserviceIndexRoute,
  AdminAdminActivityActivitySummaryRoute:
    AdminAdminActivityActivitySummaryRoute,
  AdminAdminEmployeeStaffserviceSummaryRoute:
    AdminAdminEmployeeStaffserviceSummaryRoute,
  AdminAdminNewsNewsSummaryRoute: AdminAdminNewsNewsSummaryRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserActivityIdRoute: typeof UserActivityIdRoute
  UserItaCreateRoute: typeof UserItaCreateRoute
  UserNewsIdRoute: typeof UserNewsIdRoute
  UserActivityIndexRoute: typeof UserActivityIndexRoute
  UserComplaintIndexRoute: typeof UserComplaintIndexRoute
  UserDocumentIndexRoute: typeof UserDocumentIndexRoute
  UserItaIndexRoute: typeof UserItaIndexRoute
  UserNewsIndexRoute: typeof UserNewsIndexRoute
  UserServiceIndexRoute: typeof UserServiceIndexRoute
  UserAboutContactIndexRoute: typeof UserAboutContactIndexRoute
  UserAboutDoctorIndexRoute: typeof UserAboutDoctorIndexRoute
  UserAboutHistoryIndexRoute: typeof UserAboutHistoryIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserActivityIdRoute: UserActivityIdRoute,
  UserItaCreateRoute: UserItaCreateRoute,
  UserNewsIdRoute: UserNewsIdRoute,
  UserActivityIndexRoute: UserActivityIndexRoute,
  UserComplaintIndexRoute: UserComplaintIndexRoute,
  UserDocumentIndexRoute: UserDocumentIndexRoute,
  UserItaIndexRoute: UserItaIndexRoute,
  UserNewsIndexRoute: UserNewsIndexRoute,
  UserServiceIndexRoute: UserServiceIndexRoute,
  UserAboutContactIndexRoute: UserAboutContactIndexRoute,
  UserAboutDoctorIndexRoute: UserAboutDoctorIndexRoute,
  UserAboutHistoryIndexRoute: UserAboutHistoryIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
