/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as UserServiceIndexRouteImport } from './routes/_user/service/index'
import { Route as UserNewsIndexRouteImport } from './routes/_user/news/index'
import { Route as UserDocumentIndexRouteImport } from './routes/_user/document/index'
import { Route as UserComplaintIndexRouteImport } from './routes/_user/complaint/index'
import { Route as UserActivityIndexRouteImport } from './routes/_user/activity/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as UserNewsIdRouteImport } from './routes/_user/news/$id'
import { Route as UserActivityIdRouteImport } from './routes/_user/activity/$id'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as UserAboutHistoryIndexRouteImport } from './routes/_user/about/history/index'
import { Route as UserAboutDoctorIndexRouteImport } from './routes/_user/about/doctor/index'
import { Route as UserAboutContactIndexRouteImport } from './routes/_user/about/contact/index'
import { Route as AdminAdminNewsIndexRouteImport } from './routes/_admin/admin/news/index'
import { Route as AdminAdminLoginIndexRouteImport } from './routes/_admin/admin/login/index'
import { Route as AdminAdminActivityIndexRouteImport } from './routes/_admin/admin/activity/index'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserServiceIndexRoute = UserServiceIndexRouteImport.update({
  id: '/service/',
  path: '/service/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserNewsIndexRoute = UserNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDocumentIndexRoute = UserDocumentIndexRouteImport.update({
  id: '/document/',
  path: '/document/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserComplaintIndexRoute = UserComplaintIndexRouteImport.update({
  id: '/complaint/',
  path: '/complaint/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserActivityIndexRoute = UserActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserNewsIdRoute = UserNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserActivityIdRoute = UserActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UserAboutHistoryIndexRoute = UserAboutHistoryIndexRouteImport.update({
  id: '/about/history/',
  path: '/about/history/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAboutDoctorIndexRoute = UserAboutDoctorIndexRouteImport.update({
  id: '/about/doctor/',
  path: '/about/doctor/',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAboutContactIndexRoute = UserAboutContactIndexRouteImport.update({
  id: '/about/contact/',
  path: '/about/contact/',
  getParentRoute: () => UserRouteRoute,
} as any)
const AdminAdminNewsIndexRoute = AdminAdminNewsIndexRouteImport.update({
  id: '/admin/news/',
  path: '/admin/news/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminLoginIndexRoute = AdminAdminLoginIndexRouteImport.update({
  id: '/admin/login/',
  path: '/admin/login/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminActivityIndexRoute = AdminAdminActivityIndexRouteImport.update({
  id: '/admin/activity/',
  path: '/admin/activity/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/activity/$id': typeof UserActivityIdRoute
  '/news/$id': typeof UserNewsIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/activity/': typeof UserActivityIndexRoute
  '/complaint/': typeof UserComplaintIndexRoute
  '/document/': typeof UserDocumentIndexRoute
  '/news/': typeof UserNewsIndexRoute
  '/service/': typeof UserServiceIndexRoute
  '/admin/activity/': typeof AdminAdminActivityIndexRoute
  '/admin/login/': typeof AdminAdminLoginIndexRoute
  '/admin/news/': typeof AdminAdminNewsIndexRoute
  '/about/contact/': typeof UserAboutContactIndexRoute
  '/about/doctor/': typeof UserAboutDoctorIndexRoute
  '/about/history/': typeof UserAboutHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof UserIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/activity/$id': typeof UserActivityIdRoute
  '/news/$id': typeof UserNewsIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/activity': typeof UserActivityIndexRoute
  '/complaint': typeof UserComplaintIndexRoute
  '/document': typeof UserDocumentIndexRoute
  '/news': typeof UserNewsIndexRoute
  '/service': typeof UserServiceIndexRoute
  '/admin/activity': typeof AdminAdminActivityIndexRoute
  '/admin/login': typeof AdminAdminLoginIndexRoute
  '/admin/news': typeof AdminAdminNewsIndexRoute
  '/about/contact': typeof UserAboutContactIndexRoute
  '/about/doctor': typeof UserAboutDoctorIndexRoute
  '/about/history': typeof UserAboutHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/_user/': typeof UserIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_user/activity/$id': typeof UserActivityIdRoute
  '/_user/news/$id': typeof UserNewsIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_user/activity/': typeof UserActivityIndexRoute
  '/_user/complaint/': typeof UserComplaintIndexRoute
  '/_user/document/': typeof UserDocumentIndexRoute
  '/_user/news/': typeof UserNewsIndexRoute
  '/_user/service/': typeof UserServiceIndexRoute
  '/_admin/admin/activity/': typeof AdminAdminActivityIndexRoute
  '/_admin/admin/login/': typeof AdminAdminLoginIndexRoute
  '/_admin/admin/news/': typeof AdminAdminNewsIndexRoute
  '/_user/about/contact/': typeof UserAboutContactIndexRoute
  '/_user/about/doctor/': typeof UserAboutDoctorIndexRoute
  '/_user/about/history/': typeof UserAboutHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/activity/$id'
    | '/news/$id'
    | '/admin/'
    | '/activity/'
    | '/complaint/'
    | '/document/'
    | '/news/'
    | '/service/'
    | '/admin/activity/'
    | '/admin/login/'
    | '/admin/news/'
    | '/about/contact/'
    | '/about/doctor/'
    | '/about/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/activity/$id'
    | '/news/$id'
    | '/admin'
    | '/activity'
    | '/complaint'
    | '/document'
    | '/news'
    | '/service'
    | '/admin/activity'
    | '/admin/login'
    | '/admin/news'
    | '/about/contact'
    | '/about/doctor'
    | '/about/history'
  id:
    | '__root__'
    | '/_admin'
    | '/_user'
    | '/_user/'
    | '/_admin/admin/dashboard'
    | '/_user/activity/$id'
    | '/_user/news/$id'
    | '/_admin/admin/'
    | '/_user/activity/'
    | '/_user/complaint/'
    | '/_user/document/'
    | '/_user/news/'
    | '/_user/service/'
    | '/_admin/admin/activity/'
    | '/_admin/admin/login/'
    | '/_admin/admin/news/'
    | '/_user/about/contact/'
    | '/_user/about/doctor/'
    | '/_user/about/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/service/': {
      id: '/_user/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof UserServiceIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/news/': {
      id: '/_user/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof UserNewsIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/document/': {
      id: '/_user/document/'
      path: '/document'
      fullPath: '/document/'
      preLoaderRoute: typeof UserDocumentIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/complaint/': {
      id: '/_user/complaint/'
      path: '/complaint'
      fullPath: '/complaint/'
      preLoaderRoute: typeof UserComplaintIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/activity/': {
      id: '/_user/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof UserActivityIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/news/$id': {
      id: '/_user/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof UserNewsIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/activity/$id': {
      id: '/_user/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof UserActivityIdRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_user/about/history/': {
      id: '/_user/about/history/'
      path: '/about/history'
      fullPath: '/about/history/'
      preLoaderRoute: typeof UserAboutHistoryIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/about/doctor/': {
      id: '/_user/about/doctor/'
      path: '/about/doctor'
      fullPath: '/about/doctor/'
      preLoaderRoute: typeof UserAboutDoctorIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/about/contact/': {
      id: '/_user/about/contact/'
      path: '/about/contact'
      fullPath: '/about/contact/'
      preLoaderRoute: typeof UserAboutContactIndexRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_admin/admin/news/': {
      id: '/_admin/admin/news/'
      path: '/admin/news'
      fullPath: '/admin/news/'
      preLoaderRoute: typeof AdminAdminNewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/login/': {
      id: '/_admin/admin/login/'
      path: '/admin/login'
      fullPath: '/admin/login/'
      preLoaderRoute: typeof AdminAdminLoginIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/activity/': {
      id: '/_admin/admin/activity/'
      path: '/admin/activity'
      fullPath: '/admin/activity/'
      preLoaderRoute: typeof AdminAdminActivityIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminActivityIndexRoute: typeof AdminAdminActivityIndexRoute
  AdminAdminLoginIndexRoute: typeof AdminAdminLoginIndexRoute
  AdminAdminNewsIndexRoute: typeof AdminAdminNewsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminActivityIndexRoute: AdminAdminActivityIndexRoute,
  AdminAdminLoginIndexRoute: AdminAdminLoginIndexRoute,
  AdminAdminNewsIndexRoute: AdminAdminNewsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserIndexRoute: typeof UserIndexRoute
  UserActivityIdRoute: typeof UserActivityIdRoute
  UserNewsIdRoute: typeof UserNewsIdRoute
  UserActivityIndexRoute: typeof UserActivityIndexRoute
  UserComplaintIndexRoute: typeof UserComplaintIndexRoute
  UserDocumentIndexRoute: typeof UserDocumentIndexRoute
  UserNewsIndexRoute: typeof UserNewsIndexRoute
  UserServiceIndexRoute: typeof UserServiceIndexRoute
  UserAboutContactIndexRoute: typeof UserAboutContactIndexRoute
  UserAboutDoctorIndexRoute: typeof UserAboutDoctorIndexRoute
  UserAboutHistoryIndexRoute: typeof UserAboutHistoryIndexRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserIndexRoute: UserIndexRoute,
  UserActivityIdRoute: UserActivityIdRoute,
  UserNewsIdRoute: UserNewsIdRoute,
  UserActivityIndexRoute: UserActivityIndexRoute,
  UserComplaintIndexRoute: UserComplaintIndexRoute,
  UserDocumentIndexRoute: UserDocumentIndexRoute,
  UserNewsIndexRoute: UserNewsIndexRoute,
  UserServiceIndexRoute: UserServiceIndexRoute,
  UserAboutContactIndexRoute: UserAboutContactIndexRoute,
  UserAboutDoctorIndexRoute: UserAboutDoctorIndexRoute,
  UserAboutHistoryIndexRoute: UserAboutHistoryIndexRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
